### ISSUE TITLE
Server crashes as soon as a player joins, with no error message

### ISSUE THREAD

**Issue by brunofin** [DeathCradle/Terraria-s-Dedicated-Server-Mod#106]
As the title says, the server crashes as soon as a player joins, with no error message. This wasn't happening before on a server running 24/7, with two daily restarts (with world save). Creating a new world changes nothing. Joining with a newly created character is still causing the server to crash.

Running TDSM Rebind core build 2b on Ubuntu Server 14.04 64-bits.

Part of the log: http://pastebin.com/UX82AAcb

**Comment by D1G1T4L3CH0** [comment]
Make sure your permissions in Linux for that directory and it's sub-directories are set properly to allow the user running the server full control. By default, my /opt directory is root owned in Ubuntu.

Other than that, I don't know what the issue could be. We'll see if @DeathCradle can make sense of it. :wink: I'll test this on my own server though. I may have forgot to test b2 on Linux.

**Comment by D1G1T4L3CH0** [comment]
Ok tested release b2 on Linux. it seems to be working properly for me. You can jump on my test server if you want some time to check if it's just your character or whatever. It's up at digitalecho.ga:8888

I'm running Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1) and Ubuntu 14.04.1 LTS Release 14.04 Codename trusty.

**Comment by brunofin** [comment]
Thanks for your comments! :) This server was running fine until 2 days ago, when I installed on the same machine a Counter-Strike: Source server. I can't see the relation between them but that was the only change.

Before I was thinking that maybe someone joined the server and did something buggy in the world, which got saved and couldn't be loaded anymore, but creating a new world still crashes the server.

Besides from that, I'll also check if I changed user permission for the /opt/servers directory by mistake, but I don't remember messing with that.

**Comment by D1G1T4L3CH0** [comment]
I see this in my console:
```
7:34 AM Serv> <IP REMOVED>:18981 is connecting...
4/2/2015 4:17:34 AM Pool> <IP REMOVED>:18981: disconnecting for: Client sent invalid network message (17735 | 84)
4/2/2015 4:17:34 AM Serv> <IP REMOVED>:12325 is connecting...
4/2/2015 4:17:34 AM Serv> ArgsPool<RecvArgs> capacity is now: 2.
4/2/2015 4:17:34 AM Pool> <IP REMOVED>:18981: connection closed (ConnectionAborted).
4/2/2015 4:17:34 AM Pool> ArgsPool<KickArgs> capacity is now: 1.
4/2/2015 4:17:34 AM Serv> <IP REMOVED>:31246 is connecting...
4/2/2015 4:17:46 AM Pool> <IP REMOVED>:12325: connection closed (Disconnecting).
4/2/2015 4:17:46 AM Pool> <IP REMOVED>:31246: connection closed (Disconnecting).
```
I'm guessing it was you... Did you actually connect and was able to play? I'm mostly wondering about that `invalid network message` line.

**Comment by brunofin** [comment]
Sorry it wasn't me. But I saw this is my console too from some clients trying to connect, and it also happened with me a couple of times. When it happens, I'm not able to connect and play, instead I get a message in the connection screen, I can't recall it perfectly but I think it was something like "The server sent an invalid message".

About file permissions, I've run `chmod a+rwx -R .` in my `/opt/servers/` directory (where I keep my TDSM installation), and the server still crashes when a client connects.

I'm curious what could have changed, is there any file that server writes to or reads from, that could have got corrupted? During the server's first days, I wasn't finishing it properly between reboots with the `exit` command.

**Comment by D1G1T4L3CH0** [comment]
Try making a new directory somewhere and just extract the b2 files there making a new server. Then run it and try connecting. That would rule out corrupted files. I've discussed this with @DeathCradle and he is looking into that invalid network message, but I'm thinking he don't really have any idea what your issue could be for the crashing yet.

**Comment by DeathCradle** [comment]
Sorry for the ridiculously late reply. Try using "mono --trace=program tdsm.exe" to get some indication of an error.

**Comment by DeathCradle** [comment]
@brunofin, has this issue been resolved? There's been significant changes and a few unexpected crashes fixed. If we don't hear back from you soon I'll go ahead and close this.

**Comment by brunofin** [comment]
Hey, sorry. My server is actually down since some time, but I would like to
help. I'll update it and put is up this weekend for as long as possible. If
this happens again I'll let you know.

**Comment by DeathCradle** [comment]
Great! thanks for the quick response @brunofin!

**Comment by machtgelust** [comment]
I'm getting a similar problem. 

"disconnecting for: Client sent invalid network message (184614931 | 84)"

![capture](https://cloud.githubusercontent.com/assets/13321472/8659927/8a09e22e-2973-11e5-9d92-ddf152d76ed0.PNG)
Terraria client version 1.3.0.4
TDSM v. 1.1.2 B37

When I run it with the --trace=program option, my network utilization goes way up and lags the ssh session until i kill it. 

![trace](https://cloud.githubusercontent.com/assets/13321472/8660093/7449f40a-2974-11e5-971d-365cadd3a906.PNG)

The "Native Stacktrace" part is where I killed it with kill -6.

**Comment by DeathCradle** [comment]
@machtgelust you are using a very old version of tdsm. Please find the latest in the Binaries folder.

**Comment by D1G1T4L3CH0** [comment]
@machtgelust 
You can go to the repo [home page](https://github.com/DeathCradle/Terraria-s-Dedicated-Server-Mod) and click **Download ZIP**. Then extract those files and look inside the **Binaries folder**. You can even run it from there.

**Comment by machtgelust** [comment]
yeah i  had figured it out thanks :) 

though now that you mention it, when i run it and log in there are no blocks. i just fall into the abyss until i hit the bottom... should i make a new thread?

**Comment by DeathCradle** [comment]
Yes that would be great thanks @machtgelust. Can't you also provide screenshots and system info. I'm not sure if this is a vanilla bug our tdsm. I think tshock is having something similar.

**Comment by machtgelust** [comment]
sorry, see my edit. all my problems were between keyboard and chair. sorry for hijacking this thread

**Comment by DeathCradle** [comment]
Haha, all good mate. I'm glad it was a simple fix.

**Comment by DeathCradle** [comment]
I think I'll go ahead and close this issue off anyway, however if @brunofin or anyone else had this issue still please do open a new issue.
