### ISSUE TITLE
Event "Summon"

### ISSUE THREAD

**Issue by nikkimas** [DeathCradle/Terraria-s-Dedicated-Server-Mod#107]
Is there a way to "Summon" or force start an Event like Solar Eclipse etc.?

**Comment by D1G1T4L3CH0** [comment]
There is the invasion command, However that's not really what you are looking for. It just allows starting invasions. I think @DeathCradle was planning that. Hopefully so, because it's a good feature.

If you are a developer, you might be able to do this in a plugin.

**Comment by DeathCradle** [comment]
@D1G1T4L3CH0 Unfortunately a plugin probably would have to do some dirty stuff to get it to work correctly (e.g. what if the world was not hard mode?).

So I've made a change to the patcher to inject a flag "tdsm.api.Callbacks.MainCallback.StartEclipse". When the flag is set the eclipse will start (providing the time is correct).

@nikkimas Within the TDSM Core we now have a new command to invoke an eclipse. It is: worldevent eclipse

Note: We still haven't fully tested this command. When we confirm it's working we are going to release a new public build. But feel free to compile from source if you want it earlier!

Commit: a4c4abc93d0738a4ccc6f381268c0726d9306b2

**Comment by nikkimas** [comment]
okay , I'll just wait :). Oh btw, is there an Auto Update, or do I have to do it manually?

**Comment by DeathCradle** [comment]
Sorry, currently there's no auto update. We'll take it into consideration for the next release though, as it may stem from the hearbeat server/repo (which we're introducing this release).

**Comment by nikkimas** [comment]
okay, and where do I see the current version installed on my Server?

**Comment by DeathCradle** [comment]
Typically in the title of the console or upon startup will show the API version.
For plugins you must do "plugin info <plugin name>" (e.g. plugin info "tdsm core module")
I am also pushing a new commit so you can simply type "version" to see both the terraria version and the api version.
In addition when you use "plugins" it will list the version in brackets beside the plugin name.

![image](https://cloud.githubusercontent.com/assets/776327/8017387/ce69c7bc-0c37-11e5-8dd2-04252ab7c5f2.png)

**Comment by nikkimas** [comment]
hmmm, when I type in "plugins" it just shows this: 
![image](https://cloud.githubusercontent.com/assets/11046364/8020145/b8761d3e-0c6e-11e5-8854-88e69800ac27.png)
 :D Is it because it's on Linux, or an old Version?

**Comment by D1G1T4L3CH0** [comment]
He was talking about the latest commit to source, not the release build. Those changes should be in the next release though. :)
