### ISSUE TITLE
TDSM website

### ISSUE THREAD

**Issue by skylord123** [DeathCradle/Terraria-s-Dedicated-Server-Mod#108]
TDSM is a great tool for Terraria and really needs a website.

I am going to get back into hosting a server using TDSM and would like to be able to contribute plugins and help other people out. I feel like TDSM is the best server hosting solution for Terraria that is currently out there.

If server costs are an issue I am willing to use my own servers to host the TDSM website. I am even willing to sign a contract if that is what it comes down to. I really want to help TDSM become great again any way I can. 

I do web development for a living. I am a professional PHP programmer (check out my GitHub account, I don't have much open source code but I try to contribute). I am willing to help develop a nice website for TDSM as well as help host it. Any of the work done will be owned by TDSM. 

I sent @DeathCradle an E-Mail but I don't know if he has read it yet, or found it legit. 

Also on a side note I really want to help contribute to TDSM. I don't know anything about the programming language it is written in but I really want to start learning by starting off with plugins and advancing. Would be great if we had a website to share my progress and what I used to learn with other people. 

Anyways, let me know what you guys think. I really want TDSM to be a huge success :)

**Comment by DeathCradle** [comment]
For readers, Skylord123 was able to get in contact with me be other means.

**Comment by D1G1T4L3CH0** [comment]
Sounds like a great idea. Glad to see some helping hands. :) There is already some progress on such website, @DeathCradle is doing it. But maybe he wouldn't mind a little help with it. :smile:

**Comment by skylord123** [comment]
@D1G1T4L3CH0 Yes, I am looking forward to helping. I have been  browsing over old plugin code and trying things out. I may wait until we have a more stable version of TDSM and a couple plugins (or at least one) that I can use for reference.

I'm going to see if I can start coding a website or something this weekend.

**Comment by D1G1T4L3CH0** [comment]
There are already example plugins working. :smile: And there is my simple rename world plugin mainly used as a tutorial, but it's useful if you ever find yourself needing that. However there is a new 'var' command since I it, that basically depreciates my plugin heh.

Plugin Examples: https://github.com/DeathCradle/Terraria-s-Dedicated-Server-Mod/tree/master/PluginExamples
RenWorld: https://github.com/D1G1T4L3CH0/TDSM-RenWorld-Plugin
