### ISSUE TITLE
1.3.0.3 not working

### ISSUE THREAD

**Issue by ComputeLinux** [DeathCradle/Terraria-s-Dedicated-Server-Mod#113]
Title.

**Comment by D1G1T4L3CH0** [comment]
The current released version isn't working with the new version of Terraria. Right now there is no release for 1.3 but it is available in the binaries directory. :) Just go in there and grab the files. Maybe one of us will make a release soon, if so, I'll post here and let you know. Just keep an eye on https://github.com/DeathCradle/Terraria-s-Dedicated-Server-Mod/releases for a new release.

**Comment by ComputeLinux** [comment]
I ment that version, sorry for not being specific.

**Comment by D1G1T4L3CH0** [comment]
I'm assuming (from your name) that you are trying to run on Linux? Could you provide more information on the problem such as error messages, steps to reproduce the error, and your system information with mono version and os version? Thanks.

**Comment by ComputeLinux** [comment]
The server's version is 1.3.0.2, Terraria's version is 1.3.0.3

**Comment by DeathCradle** [comment]
Just updated the binaries folder with the latest.

**Comment by ComputeLinux** [comment]
I'm hosting on linux and can't run commands.

**Comment by ComputeLinux** [comment]
just got fixed.

**Comment by DeathCradle** [comment]
Excellent news, I'm going ahead and closing this.
