### ISSUE TITLE
Server log spam

### ISSUE THREAD

**Issue by nikkimas** [DeathCradle/Terraria-s-Dedicated-Server-Mod#114]
As the title says.
When players are connected, the console/logs get spammed with stuff like this:
![image](https://cloud.githubusercontent.com/assets/11046364/8501016/eaacea92-21a1-11e5-9813-3f9edfed4c46.png)

Am I doing something wrong?

**Comment by Gurken2108** [comment]
Too, I've created a crontab temporary:

crontab -e
*/3 * * * * rm /home/tdsm/tdsm/Binaries/Data/server*.log

**Comment by DeathCradle** [comment]
Fixed!

**Comment by nikkimas** [comment]
Thank you!
