### ISSUE TITLE
[Sometimes] Server crash after /spawnboss

### ISSUE THREAD

**Issue by Gurken2108** [DeathCradle/Terraria-s-Dedicated-Server-Mod#116]
I've found a thread like that too, but i created a new one for 1.3.0.3.

After /spawnboss eye of cthulhu for example, the server crashed sometimes. I don't know if this is a crash only on the Raspberry Pi 2 or on the software.

Server Status with a medium Map, 3 Players, screen, TDSM.exe and webmin running:
http://puu.sh/iN10V/7356ee4fb2.png
Hardwarespeicher = RAM
Virtueller Speicher = SWP RAM
Laufende Prozesse = Running Process

The server is only laggy on the mob. If we break something everything is okay, we get the block instant.

**Comment by DeathCradle** [comment]
I haven't had a chance to work on the spawnboss command so I'd say it's just broken, I'll keep this open for a reminder!

**Comment by DeathCradle** [comment]
Seems this is a duplicate issue, refer to #98 as it was the older issue.
