### ISSUE TITLE
Random server "crash"

### ISSUE THREAD

**Issue by Gurken2108** [DeathCradle/Terraria-s-Dedicated-Server-Mod#118]
On my RP2 is the most thing working fine. But there are a few problems with the netcode (also in tshock) and a random Server crash. After the "crash" the console is refreshing but a command like save-all isn't working. In the log i can't find an error.

**Comment by DeathCradle** [comment]
If there is no crash in the log are you able to run "mono --trace=program tdsm.exe"? If there's an exception that trace flag should help it be shown in the console.
Unfortunately it wi take some time, you may want to grab a coffee while it loads the world.

**Comment by Gurken2108** [comment]
I will test it at noon (GMT +2 :D) today. I hope I didn't forget it ^^

**Comment by DeathCradle** [comment]
It's been a while with no response, so I'm going ahead and closing off this issue. The new connection code is in and some crashes have been fixed. If this issue is not actually resolved, please do create another.
