### ISSUE TITLE
Join Server "Welcome to" Message Missing World Name

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#123]
Upon connection to server with the motd option in the server config file commented out, server displays a "Welcome to" message with nothing following it.
![2015-07-07_00003](https://cloud.githubusercontent.com/assets/1936606/8559460/1a84e36e-24db-11e5-9ff2-710bd071b012.jpg)

Normally I would expect the world name to show there.

**Comment by DeathCradle** [comment]
Commit #4ee7efcdecc21a2ae9ef870399ea480406ded5e1 should fix this.

**Comment by D1G1T4L3CH0** [comment]
resolved
