### ISSUE TITLE
'settle' Command "Permissions Error" In-Game

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#124]
The settle command seemingly cannot be used. There is a permission error message every time it's used in-game.

Works fine in console.

This command used to work from in-game.

**Comment by DeathCradle** [comment]
It's now defaulted to OP in de04997ba518e6a7557cf1760e094020d977b5a9

**Comment by D1G1T4L3CH0** [comment]
resolved
