### ISSUE TITLE
Cannot delete worlds from server console

### ISSUE THREAD

**Issue by parkervcp** [DeathCradle/Terraria-s-Dedicated-Server-Mod#125]
When you start a server and it asks to choose a world you can't delete the world.

You can manually delete the world still.

**Comment by D1G1T4L3CH0** [comment]
Confirmed on Linux. Works as expected on WIndows.

**Comment by ZeroKnight** [comment]
>Confirmed on Linux. Works as expected on Windows
Could be a case-sensitivity problem? Maybe path separator issue? Just guessing.

**Comment by DeathCradle** [comment]
I've just had a look. They are using a windows specific function (moving to recycle bin using the win32 api) and not the typical permanent delete.

**Comment by DeathCradle** [comment]
A patch should be available in the Binaries directory.
Affecting commit: b8e0180a98a19232938d7e901a13124dcd8afd1b

**Comment by D1G1T4L3CH0** [comment]
resolved
