### ISSUE TITLE
Bug issue connection 1.3.0.4

### ISSUE THREAD

**Issue by hunterpl** [DeathCradle/Terraria-s-Dedicated-Server-Mod#128]
Hello Dear developers

SOCK: System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
  at System.Buffer.BlockCopy (System.Array src, Int32 srcOffset, System.Array dst, Int32 dstOffset, Int32 count) [0x00000] in <filename unknown>:0
  at tdsm.api.ClientConnection.DespatchData (System.Byte[] buff) [0x00000] in <filename unknown>:0
7/10/2015 3:16:04 AM Pool> 178.37.190.31:58381: connection closed (Shutdown).
7/10/2015 3:16:08 AM Pool> 178.37.190.31:58384 is connecting...
7/10/2015 3:16:08 AM Pool> Log message repeated 1 times
7/10/2015 3:16:08 AM Pool> Error on message Terraria.MessageBuffer
7/10/2015 3:16:11 AM Pool> buff: 1440
7/10/2015 3:16:11 AM Pool> test.Buffer.Length: 1024
7/10/2015 3:16:11 AM Pool> test.Offset: 0
7/10/2015 3:16:11 AM Pool> test.Size: 1024
7/10/2015 3:16:11 AM Pool> SOCK: System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
  at System.Buffer.BlockCopy (System.Array src, Int32 srcOffset, System.Array dst, Int32 dstOffset, Int32 count) [0x00000] in <filename unknown>:0
  at tdsm.api.ClientConnection.DespatchData (System.Byte[] buff) [0x00000] in <filename unknown>:0
7/10/2015 3:16:38 AM Pool> 178.37.190.31:58384: connection closed (Shutdown).

Some people can't join due of this issue of connection and after few minutes server going to crash and freeze console, when i try connect or someone to my server it say " server found " that's all.

**Comment by D1G1T4L3CH0** [comment]
Ah. so i'm not alone hah. The team couldn't see this and I was thinking it's just me. Good news is that since your post we now know it's a real thing, and can begin work on fixing it. Thanks.

**Comment by D1G1T4L3CH0** [comment]
This issue seems to be resolved with the latest binaries. Please check.

**Comment by hunterpl** [comment]
Hello thread can be closed we can entry now :) thank you so much
