### ISSUE TITLE
Extra 'Worlds' directory created in tdsm.exe working directory with `worldpath` specified in config

### ISSUE THREAD

**Issue by ZeroKnight** [DeathCradle/Terraria-s-Dedicated-Server-Mod#133]
Even if `worldpath` is set in the server config, TDSM will create an extra empty 'Worlds' directory in the working directory where tdsm.exe was run from. Note it will still end up looking for worlds and saving them where specified in the config.

Might be related to #129?

Example:

     [tdsm-git/Binaries] $ mono --server ./tdsm.exe -config Data/serverconfig.txt    # worldpath set to ../../Worlds in config
     # exit server
     [tdsm-git/Binaries] $ ls
     [...] Worlds

**Comment by D1G1T4L3CH0** [comment]
Yeahs this is true. I've seen this since the beginning of 1.3 tdsm and just kept forgetting to say anything about it heh. Thanks for posting.

**Comment by Stickiler** [comment]
Fixed
