### ISSUE TITLE
Some commands do nothing when used in game

### ISSUE THREAD

**Issue by ZeroKnight** [DeathCradle/Terraria-s-Dedicated-Server-Mod#134]
Apologies if this is known and/or in-development, but the following commands appear to have no effect when used in game:

* ban
* clear
* dawn
* dusk
* itemrej (does nothing in console either)
* maxplayers
* midnight
* motd
* noon
* password
* port
* restart
* save (save-all works)
* version

**Comment by DeathCradle** [comment]
Fixing them now. By default those are vanilla commands and were expected to be console only. Recently I allowed them to be used by operators and didn't remove the restriction.

**Comment by DeathCradle** [comment]
Commit c525a9dd484060d7087b2e56ab2e929f49cb216f should fix this. Can you confirm by grabbing the latest binaries?

**Comment by ZeroKnight** [comment]
* `save` does not report in game that it is saving like `save-all` does; ie. no "Saving world..." and "Saving Complete." messages.

* `dawn`|`dusk`|`noon`|`midnight` commands work, but do not report the "Time set to X" messages in game (it does to console though).

* `restart` doesn't seem to work at all, actually; neither in game nor console

The following commands return output to the console, but not in game:

* maxplayers
* motd
* password (also does not report the changed password in game)
* port
* version

**Comment by DeathCradle** [comment]
Thanks! I overlooked that, sorry. However restart is broken and so i've disabled it. The latest binaries up.
Commit: fc8b6cc05bcdbd69a3addab2cb573a26405056e1

**Comment by ZeroKnight** [comment]
Everything looks good here, @DeathCradle :)

**Comment by DeathCradle** [comment]
Fantastic, thank you!
