### ISSUE TITLE
Restrict password on connect

### ISSUE THREAD

**Issue by DeathCradle** [DeathCradle/Terraria-s-Dedicated-Server-Mod#135]
This is a reminder for me to add two hooks before B3 release in order for restrict to fully work:
- PlayerDataReceived
- PlayerPassReceived

**Comment by DeathCradle** [comment]
This needs testing now.

**Comment by skylord123** [comment]
When I type incorrect password I get the error stating the password was wrong, but when I put the correct password I just get disconnected with "timed out" message.

**Comment by DeathCradle** [comment]
@skylord123 I've removed a duplicate timeout check, does this fix it for you?

**Comment by D1G1T4L3CH0** [comment]
seems resolved for me.
