### ISSUE TITLE
Crash report. Randomly occurs.

### ISSUE THREAD

**Issue by benneh87** [DeathCradle/Terraria-s-Dedicated-Server-Mod#137]
Hey
Before the 1.3.0.4 update the server was running like a dream. Since then I regularly get the below:

System.NullReferenceException: Object reference not set to an instance of an object
  at Terraria.Player.Ghost () [0x00000] in <filename unknown>:0 
  at Terraria.Player.Update (Int32 i) [0x00000] in <filename unknown>:0 
  at Terraria.Main.Update (Microsoft.Xna.Framework.GameTime gameTime) [0x00000] in <filename unknown>:0 
  at Terraria.Main.DedServ () [0x00000] in <filename unknown>:0 
  at Terraria.Program.LaunchGame (System.String[] args) [0x00000] in <filename unknown>:0 

Im running a debian server. The server uses alot more RAM than before.

**Comment by DeathCradle** [comment]
I'm thinking this may not be related to RAM. Can you please try the latest binaries, or any commit after acc6603cf8d6789d19c636062c677644dee705e4?

On the note of memory, It's planned to be fixed, just been busy with higher priority items.

**Comment by benneh87** [comment]
I took the latest master version yesterday morning.  Which I believe is after the acc6603.
In work currently so I won't be able to check quite yet.

Sent from my Sony Xperia™ smartphone

---- Luke wrote ----

I'm thinking this may not be related to RAM. Can you please try the latest binaries, or any commit after acc6603cf8d6789d19c636062c677644dee705e4?

On the note of memory, It's planned to be fixed, just been busy with higher priority items.

---

**Comment by DeathCradle** [comment]
Any news?

**Comment by benneh87** [comment]
Sorry been rather busy lately.  It's not happened since so I'm not sure what has been causing it.

---- Luke wrote ----

Any news?

---

**Comment by DeathCradle** [comment]
I'd say the fix I put in was the actual cause, so I'll go ahead an close this off. Thanks!
