### ISSUE TITLE
Empty config file / no spaces

### ISSUE THREAD

**Issue by skylord123** [DeathCradle/Terraria-s-Dedicated-Server-Mod#138]
Config files are empty when written. The restrict.properties file does not contain anything. I am able to directly add config options but if there are any spaces around the equals sign it wont work

allow-guests = true # doesnt work
allow-guests=true # does work

**Comment by DeathCradle** [comment]
Should now be fixed in 2287c05252b70662aee945773dfe8c3977578ec6

**Comment by skylord123** [comment]
@DeathCradle I will test this out tonight. Thanks bud.

**Comment by skylord123** [comment]
Tested this out, looks like all is well.

**Comment by DeathCradle** [comment]
Thanks
