### ISSUE TITLE
Bug issue with login to the server and registration

### ISSUE THREAD

**Issue by hunterpl** [DeathCradle/Terraria-s-Dedicated-Server-Mod#140]
Hello dev

People on my server can't register they have to click several times to join on my server and then type "/register password" what is required i don't know it happens from this new version after /login password always server show they auth is failed why? can you check that IP: 178.217.186.81:7777

let me know what to do, im sure is it a bug.

**Comment by D1G1T4L3CH0** [comment]
Hi, I'm not sure I understand what you are saying...

If you are having trouble with logins, do the following:
1. Remove the Restrict plugin from TDSM temporarily.
2. Run tdsm.exe without the -config option.
3. Go through the interactive setup and do NOT choose a password.

See if they can join then.

**Comment by hunterpl** [comment]
Hello
I fixed this problem by update server today. Thank you.

**Comment by D1G1T4L3CH0** [comment]
Great to hear!
