### ISSUE TITLE
Add message option for exit command

### ISSUE THREAD

**Issue by skylord123** [DeathCradle/Terraria-s-Dedicated-Server-Mod#144]
Would be nice to be able to pass a message to the exit command that people will see when they get disconnected.

IE: /exit "Restarting server. Rejoin in 5 minutes!"

**Comment by D1G1T4L3CH0** [comment]
Good idea. It sounds like a plugin idea. but would be good in the base as well. Might also want an integer argument for time.

**Comment by DeathCradle** [comment]
@skylord123 I've implemented the message for the time being as the old tdsm used to send a going down message, so i figure it wasn't hard to allow the option for it too., @D1G1T4L3CH0 the time may be nice, but it could be for a plugin too; up for discussion anyway.
