### ISSUE TITLE
How to give item with prefix/modifier 

### ISSUE THREAD

**Issue by thu2468** [DeathCradle/Terraria-s-Dedicated-Server-Mod#148]

**Comment by D1G1T4L3CH0** [comment]
That's a good question. It started me to test that. It seems the -prefix option on the give command is not working, or I don't know how to use it.

Here is a list of modifiers for future reference for any dev who wants to take a look into this. http://terraria.gamepedia.com/Modifier

I've had a look at the source and it seems the give command doesn't use your input for prefix, nor does it even recognize that you have added that option. But it does use prefix from the item it finds in the definition manager which is apparently always zero. And if it needs to be int, then it seems there needs to be a lookup table with names and their ids. http://terraria.gamepedia.com/Prefix_IDs

**Comment by DeathCradle** [comment]
Same reason as #110. Give currently only supports item name since rebind. I'll add #110 and this as a build 3 requirement.

**Comment by Stickiler** [comment]
The Give command now supports prefixes, they're the final parameter, and they're optional. Help text has been updated to show the changes.

Fixed in Commit 85423eb3c65367cb1a23d4da25dd513b98d40753
