### ISSUE TITLE
Wrong user kicked for incorrect password

### ISSUE THREAD

**Issue by skylord123** [DeathCradle/Terraria-s-Dedicated-Server-Mod#150]
I was testing out if usernames were case sensitive and it looks like it is. While testing my buddy got kicked for the incorrect password and it left me at the Receiving world data message.

**Comment by elevatorguy** [comment]
was this /oplogin or /pass?
pass is restrict plugin

**Comment by D1G1T4L3CH0** [comment]
isssue was moved to restrict repo

**Comment by DeathCradle** [comment]
This was TDSM: 1ed4b97d9094c938d342af938e0cb9f4d42652dd
