### ISSUE TITLE
/pass not updating pass

### ISSUE THREAD

**Issue by skylord123** [DeathCradle/Terraria-s-Dedicated-Server-Mod#152]
This may be related to restrict only, so this may be the wrong place to put this..

Anyways my buddy tried changing his pass with /pass and it didn't change it.

**Comment by DeathCradle** [comment]
Is this fixed?

**Comment by elevatorguy** [comment]
This has gotta be restrict only.

**Comment by D1G1T4L3CH0** [comment]
isssue was moved to restrict repo
