### ISSUE TITLE
`help` Command Should Show Only Permitted Commands

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#165]
Using the help command, a player should only see the commands available to them as defined by permissions. This is not the case as they can see every command in TDSM.

**Comment by DeathCradle** [comment]
Should be in fixed in 4f1b7d1dc9741e6254e1a07c3dfa2d8b1544cb3a, can you confirm?

**Comment by DeathCradle** [comment]
Build 4 fixed this.
