### ISSUE TITLE
`list` Command Only Works Once In Console

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#169]
The `list` command seems to behave differently for console than for a player in game. In console, it will not list the online players more than one time without first using some other command.

The same happens with the other variants of this command; online, players, playing, ect...

CONSOLE:
```list
Players: DigitalEcho (1/256)
list
list
list
list
```
IN-GAME:
```/list
Players: DigitalEcho (1/256)
/list
Players: DigitalEcho (1/256)
/list
Players: DigitalEcho (1/256)
```

**Comment by DeathCradle** [comment]
Fixed for you too now?

**Comment by D1G1T4L3CH0** [comment]
yep
