### ISSUE TITLE
Compilation Under VS: DirectoryNotFoundException

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#170]
```
An unhandled exception of type 'System.IO.DirectoryNotFoundException' occurred in mscorlib.dll

Additional information: Could not find a part of the path 'E:\Windows\Documents\GitHub\Terraria-s-Dedicated-Server-Mod\tdsm-patcher\bin\x86\Debug\Plugins\TDSM.Core.dll'.
```
The directory does not exist.

**Comment by Stickiler** [comment]
Are you doing a full rebuild? A clean and build? Or just a build?

**Comment by DeathCradle** [comment]
I think he cloned, and rebuilt. The patchers Debug folder didn't have the Plugins or Library path. We just need to make sure directories are being created when we copy project files to the Debug folder from within the patcher.

**Comment by D1G1T4L3CH0** [comment]
Yep. That's it.

**Comment by DeathCradle** [comment]
Should be fixed.
