### ISSUE TITLE
Help list isn't updated upon enabling/disabling a plugin.

### ISSUE THREAD

**Issue by evil-dan2wik** [DeathCradle/Terraria-s-Dedicated-Server-Mod#172]
http://i.imgur.com/qrJv7eJ.png?1

**Comment by DeathCradle** [comment]
Thanks, this should now be fixed in the OTA fix: https://github.com/DeathCradle/Open-Terraria-API/commit/56eced541880d73c122c0c8a3fd347317377aa40
