### ISSUE TITLE
TDSM - Failed to load! No backups found.

### ISSUE THREAD

**Issue by COLDFIRE50** [DeathCradle/Terraria-s-Dedicated-Server-Mod#176]
I have the latests version of TDSM, trying to run it on a linux machine. It executes and allows me to build a world, however when I try launch the server by selecting the recently created world it tells me it has failed to load and cannot find any backups. I'm not great at working with linux but any suggestions would help. Thank you.

**Comment by D1G1T4L3CH0** [comment]
I tested on the latest Binaries, not the latest release. But I didn't find this issue. Did you break out of the server with ctrl+c before it was done saving at one point?

Did you use the latest binaries or release? Did you create a world using a config file or with the interactive server setup? Take a look in your Worlds directory like this `ls Worlds`, is there a .bak file?

**Comment by COLDFIRE50** [comment]
Well I have downloaded this https://github.com/DeathCradle/Terraria-s-Dedicated-Server-Mod/releases/download/Build-5/tdsm-build-5.zip and I directly unzipped it as a root user. I run mono tdsm.exe and it starts up the server asking me to choose a world or create one. After I select a world created using the server it asks me for maxplayers, server port etc. After wards says the following.

2015-08-15 10:28:33 AM Pool> Server state changed to: WorldLoading
2015-08-15 10:28:33 AM Pool> Log message repeated 3 times
Load failed!

I started the server on windows and whilst it created a .wld file it did not create a .bak file. ls Worlds doesn't appear to be function directory on the linux machine.

**Comment by D1G1T4L3CH0** [comment]
Just do `ls` in your tdsm directory. You should have a Worlds directory if you didn't specify a different one either by command line or config file.

Ill test your particular scenario on the latest binaries first, and if I don't see I problem I'll test using the latest release as you did.

**Comment by DeathCradle** [comment]
I've also just enabled world file debugging in the latest Binaries commit in the git. I'd recommend downloading these binaries and grabbing the exception for us to look at.

**Comment by COLDFIRE50** [comment]
Hey sorry for the late reply, like I said I am novice when it comes to using Linux, how would I go about implementing the latest Binaries commit?

**Comment by DeathCradle** [comment]
That's fine mate. You can clone the repo, or from the home page of the repo you can download the zip. One you have it just cd into Binaries and run the tdsm.exe

**Comment by COLDFIRE50** [comment]
That is in the latest TDSM server modification for Terraria 1.3.0.8? Can I post the error I am receiving now?

**Comment by COLDFIRE50** [comment]
root@gameserver:~# mono tdsm.exe
2015-08-15 02:35:35 PM Run> TDSM Rebind API build 5lr running on Mono
2015-08-15 02:35:35 PM Run> Logging started to file "/root/Data/server_20150815_                     1435.log".
2015-08-15 02:35:35 PM Run> Loading plugin from TDSM.Core.dll.
2015-08-15 02:35:35 PM Run> TDSM Rebind core build 5lr
2015-08-15 02:35:36 PM Run> TDSM Rebind core enabled
2015-08-15 02:35:36 PM Run> Server state changed to: Initialising
2015-08-15 02:35:40 PM Run> Server state changed to: Starting
Terraria Server v1.3.0.8

1               Terraria
n               New World
d <number>      Delete World

Choose World: 1
Terraria Server v1.3.0.8

Max players (press enter for 8):
Terraria Server v1.3.0.8

Server port (press enter for 7777):
Terraria Server v1.3.0.8

Automatically forward port? (y/n):
Terraria Server v1.3.0.8

Server password (press enter for none):
Terraria Server v1.3.0.8

2015-08-15 02:35:45 PM Pool> Server state changed to: WorldLoading
System.IO.FileNotFoundException: Could not load file or assembly 'WindowsBase, V                     ersion=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its                      dependencies.
File name: 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf38                     56ad364e35'
  at Terraria.IO.WorldFile.LoadWorld_Version2 (System.IO.BinaryReader reader) [0                     x00000] in <filename unknown>:0
  at TDSM.API.Callbacks.WorldFileCallback.loadWorld (Boolean loadFromCloud) [0x0                     0000] in <filename unknown>:0
System.IO.FileNotFoundException: Could not load file or assembly 'WindowsBase, V                     ersion=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its                      dependencies.
File name: 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf38                     56ad364e35'
  at Terraria.IO.WorldFile.LoadWorld_Version2 (System.IO.BinaryReader reader) [0                     x00000] in <filename unknown>:0
  at TDSM.API.Callbacks.WorldFileCallback.loadWorld (Boolean loadFromCloud) [0x0                     0000] in <filename unknown>:0
System.IO.FileNotFoundException: Could not load file or assembly 'WindowsBase, V                     ersion=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its                      dependencies.
File name: 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf38                     56ad364e35'
  at Terraria.IO.WorldFile.LoadWorld_Version2 (System.IO.BinaryReader reader) [0                     x00000] in <filename unknown>:0
  at TDSM.API.Callbacks.WorldFileCallback.loadWorld (Boolean loadFromCloud) [0x0                     0000] in <filename unknown>:0
System.IO.FileNotFoundException: Could not load file or assembly 'WindowsBase, V                     ersion=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its                      dependencies.
File name: 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf38                     56ad364e35'
  at Terraria.IO.WorldFile.LoadWorld_Version2 (System.IO.BinaryReader reader) [0                     x00000] in <filename unknown>:0
  at TDSM.API.Callbacks.WorldFileCallback.loadWorld (Boolean loadFromCloud) [0x0                     0000] in <filename unknown>:0
2015-08-15 02:35:45 PM Pool> Log message repeated 3 times
Load failed!

**Comment by COLDFIRE50** [comment]
Naturally I haven't a clue what it's telling me.

**Comment by DeathCradle** [comment]
What version of mono are you running?

**Comment by COLDFIRE50** [comment]
4.0.3

**Comment by COLDFIRE50** [comment]
I ran the normal apt-get install mono-complete

**Comment by DeathCradle** [comment]
Alright, I have another issue I need to look into for 4.0.2, so I'll install the new mono 4.0.3 tomorrow on my mac and see what I can sort out.

**Comment by COLDFIRE50** [comment]
Sounds good, let me know if I can provide any further information that might help.

**Comment by D1G1T4L3CH0** [comment]
Hey COLDFIRE50, what distro and version? because from what all I can find, 3.2.8 is the latest on Ubuntu 14 and 15 right now. Did you add a ppa?

**Comment by COLDFIRE50** [comment]
Mono JIT compiler version 4.0.3 (Stable 4.0.3.20/d6946b4 Tue Aug  4 09:42:51 UTC                2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-proj               ect.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  x86
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

I had issues with the mono version not updating from 2.10 to version 3 and so I did add a ppa, I can't seem to recall what it was that I added but if the mono version is the issue how would I go about changing it?

**Comment by evil-dan2wik** [comment]
Do you mind posting your config file?

**Comment by COLDFIRE50** [comment]
evil-dan2wik which config file? For TDSM?

**Comment by evil-dan2wik** [comment]
yes, if you use one.

**Comment by COLDFIRE50** [comment]
#this is an example config file for TerrariaServer.exe
#use the command 'TerrariaServer.exe -config serverconfig.txt' to use this conf$
#please report crashes by emailing crashlog.txt to support@terraria.org

#the following is a list of available command line parameters:

#-config <config file>                                      Specifies the confi$
#-port <port number>                                          Specifies the por$
#-players <number> / -maxplayers <number>       Sets the max number of players
#-pass <password> / -password <password>        Sets the server password
#-world <world file>                                          Load a world and $
#-autocreate <#>                                                Creates a world$
#-banlist <path>                                                Specifies the l$
#-worldname <world name>                                Sets the name of the wo$
#-secure                                                                Adds ad$
#-noupnp                                                                Disable$
#-steam                                                                 Enables$
#-lobby <friends> or <private>             Allows friends to join the server or$
#-ip <ip address>       Sets the IP address for the server to listen on


#-lobby <friends> or <private>             Allows friends to join the server or$
#-ip <ip address>       Sets the IP address for the server to listen on
#-forcepriority <priority>      Sets the process priority for this task. If thi$

#remove the # in front of commands to enable them.

#Load a world and automatically start the server.
#If your server is running linux make sure to use forward slashes for your dire$
#world=Worlds/world.wld
#world=C:\Users\YOUR_USERNAME_HERE\My Documents\My Games\Terraria\Worlds\world1$

#Creates a new world if none is found. World size is specified by: 1(small), 2($
#autocreate=1

#Sets the name of the world when using autocreate
#worldname=Terraria

#Sets the difficulty of the world when using autocreate 0(normal), 1(expert)
#difficulty=1
#Sets the difficulty of the world when using autocreate 0(normal), 1(expert)
#difficulty=1

#Sets the max number of players allowed on a server.  Value must be between 1 a$
#maxplayers=8

#Set the port number
#port=7777

#Set the server password
#password=p@55w0rd

#Set the message of the day
#motd=Please don’t cut the purple trees!

#Sets the folder where world files will be stored
#If your server is running linux make sure to use forward slashes for your dire$
#worldpath=Worlds/
#worldpath=C:\Users\Defaults\My Documents\My Games\Terraria\Worlds\

#worldpath=Worlds/
#worldpath=C:\Users\Defaults\My Documents\My Games\Terraria\Worlds\

#The location of the banlist. Defaults to "banlist.txt" in the working director$
#banlist=banlist.txt

#Adds addition cheat protection.
#secure=1

#Sets the server language 1:English, 2:German, 3:Italian, 4:French, 5:Spanish
#lang=1

#Automatically forward ports with uPNP
#upnp=1

#Reduces enemy skipping but increases bandwidth usage. The lower the number the$
#npcstream=60

#Default system priority 0:Realtime, 1:High, 2:AboveNormal, 3:Normal, 4:BelowNo$

#Default system priority 0:Realtime, 1:High, 2:AboveNormal, 3:Normal, 4:BelowNo$
priority=1

#=======================================================================
#================================================================
#                                  Additional TDSM configuration
#================================================================
#================================================================

# Enable the whitelist. The whitelist is stored in Data\whitelist.txt.
# [true|false] Default: true
usewhitelist=true

# Allows communication to the TDSM heartbeat server.
# Default data sent when heartbeat is enabled: Api version, core version, platf$
# [true|false] Default: true
heartbeat=true

heartbeat=true

# Max client queue memory size. The limit of how much data is queued to be sent$
# [Integer] Default: 1024
# Recommended between 1024 and 4096.
# [Currently not working since 1.3]
#send-queue-quota=1024

# Allows bypassing of the slot queue mechanism when the server reaches the play$
# This is typically implemented by a plugin. For example when used in conjuncti$
# {Integer] Default: 1
# [Currently not working since 1.3]
#overlimit-slots=1

# Location of a PID file to maintain.
# Comment out if not using a PID file.
#pid-file=process.pid

# If you are having issues with being kicked with forgery messages and you wish$

# If you are having issues with being kicked with forgery messages and you wish$
# NOTE: This is separate from the official server's "secure" config property.
# [true|false] Default: true
cheat-detection=true

# Server Side Characters (SSC)
# Allows the server to store and use character files instead of letting the cli$
# NOTE: Not Implemented Yet!
# [true|false] Default: true
server-side-characters=true

# DEVELOPER config. This is to disable TDSM starting it's own custom server imp$
# Set to false to use Re-Logic server code.
# [true|false] Default: true
tdsm-server-core=true

# ============================================
#                SERVER LIST

# ============================================
#                SERVER LIST
# ============================================

# Show this server on the server list.
# Default data sent when server-list is enabled: Port, max players, server name$
# Requirement: heartbeat=true
# [true|false] Default: true
#server-list=true

# The name of this server on the server list.
# Requirement: server-list=true
# This option CANNOT be blank.
server-list-name=TDSM Server

# Description of this server on the server list.
# Requirement: server-list=true
server-list-desc=This is an example of the description for use in the TDSM Serv$

server-list-desc=This is an example of the description for use in the TDSM Serv$

# Instead of displaying the IP on the server list, opt to display your domain.
# Requirement: server-list=true
#server-list-domain=tdsm.org

# ============================================
#       RCON - Remote Server Console
# ============================================

# Address for the Remote Console server to bind to.
$ Syntax: IP:PORT
# Default: 127.0.0.1:7023
rcon-bind-address=127.0.0.1:7023

# Remote console random hashing key, set to something completely random. This i$
# If this is not specified one will be generated and stored in Data\rcon.nonce
#rcon-hash-nonce=


# ============================================
#       RAWS - REMOTE ADMIN WEB SERVER
# ============================================

# Listen Address
# The address that the web server should listen on.
# To disable simply comment the line out.
# If you change the port please ensure you change the META TAG tdsm:port in /We$
# NOTE: Web server is still in development and is disabled in build 2b.
web-server-bind-address=127.0.0.1:8448

# Set to false if you wish to use another application to serve HTML files (such$
# [true|false] Default: true
web-server-serve-files=true

# The provider/your server name shown to the web user.
web-server-provider=TDSM Rebind Server Host


# The provider/your server name shown to the web user.
web-server-provider=TDSM Rebind Server Host

#================================================================
#================================================================
#                                                       Data storage
#================================================================
#================================================================
# These settings apply when you use a plugin data connector
# such as tdsm-sqlite-connector. These plugins handle how data
# is stored. There should only ever be one data connector.
#
# NOTE: These functions are not yet functional.
#       It's for an upcoming release.
#================================================================

# Sets the database to be used.
sqlite=Data Source=database.sqlite;Version=3;

sqlite=Data Source=database.sqlite;Version=3;

# Connection string for MySQL.
#mysql=Server=127.0.0.1;Database=tdsm;Uid=root;Pwd=;

**Comment by COLDFIRE50** [comment]
evil-dan2wik didn't know how to upload the file but there is the text within it.

**Comment by evil-dan2wik** [comment]
a little long, but the config isn't the issue it seems.

**Comment by COLDFIRE50** [comment]
I can also confirm that a .bak file has not been created either

**Comment by evil-dan2wik** [comment]
Is there a Worlds folder in the TDSM folder at all?

**Comment by COLDFIRE50** [comment]
Yes a world folder can be created along with the .wld file inside

**Comment by DeathCradle** [comment]
I don't think it's to do with the config. The 'WindowsBase' is a mono thing, and my 4.0.3 worked perfectly. So are you able to try to update mono again using mono-complete? It seems there are some parts missing. A little while back someone had this same issue and reinstalling added about 225 different packages.

**Comment by COLDFIRE50** [comment]
Greetings DeathCradle, I can confirm that running apt-get install mono-complete did indeed fix my problem and the server is now up and running thank you for all your help in this issue evil-dan2wik,  D1G1T4L3CH0. :)

**Comment by DeathCradle** [comment]
That's fantastic! I'll go ahead and close this off now. Thanks for using tdsm ;)
