### ISSUE TITLE
SSC: Misc Equipment Not Saved

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#179]
The equipment such as pet, lite pet, minecart, mount, and grapling hook do not save.

**Comment by DeathCradle** [comment]
I was able to save a minecart in my latest commit (6198fb1c0fe3921efa37108fe22a812399e3d68c). It also adds "miscDyes" - not sure if these are even used by the server, but kinda tired so I figured I may as well put it in and check later haha (Process is pretty simple now)

Does the equipment work for you? And is this additional dye thing required? (tbh, no idea what they are)

**Comment by D1G1T4L3CH0** [comment]
seems to be working idk what the dye thing is either
