### ISSUE TITLE
"!" Command: SPAWNNPC - Argument 3 Problem

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#181]
Issuing ` /spawnnpc 100 tesla turret` and then `/!` shows the message "spawnnpc: a connected player's name was expected for argument 3".

**Comment by DeathCradle** [comment]
Should be good in ebcf972e20e831b7330c9a7ccb7da92897d7653e

**Comment by D1G1T4L3CH0** [comment]
i dont even know now if i was typing the command exactly as i did about (not escaping the space) or not. either way, trying the same command again while escaping the space works fine, and not escaping has the argument 3 problem, of course. So closing as resolved.
