### ISSUE TITLE
EXIT Command: Server Stuck

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#182]
When executing the exit command, the server seems to get stuck and requires breaking out.
![tdsm exit stuck](https://cloud.githubusercontent.com/assets/1936606/9351153/094574fe-4625-11e5-9e8b-9fbc36db7ad0.png)

**Comment by DeathCradle** [comment]
Should be good after: 8c2538bd8c8a6298e33c86611c784bdb9b519e43

**Comment by D1G1T4L3CH0** [comment]
resolved
