### ISSUE TITLE
Multiple Players Of Same Name Are ALLOWED

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#183]
Multiple clients using a character with the same name are allowed to join at the same time. I only tested by launching two clients on the same machine.

This works with two of the same exact character and it also works with two characters of the same name.

Also, sort of unrelated, give command gives priority to the first character who joins. Just another reason this shouldn't be allowed.

One other note. We should check more than just the name because if another character just happens to have used the same name as someone who has already registered on the server, he will not be able to join since he will not have the password. If we check other things to uniquely identify the other character, we can allow registrations from same name characters or at least identify that it's a different character and send them a message about the name instead of prompt for password.

**Comment by DeathCradle** [comment]
It appears to be an issue with the API - the custom user password was not checking. Onward from ebd0445b92ebde6974b1b40f90f3f4282c6b4a81 should contain a fix. Are you able to test with and without restrict when you have time.

**Comment by D1G1T4L3CH0** [comment]
tested with and without restrict. resolved.
