### ISSUE TITLE
SSC: Not Saving Favorite Items

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#185]
SSC does not save favorite items. Set favorite item bu ALT+Click it. It will have a chain around it. Leave and rejoin and the chain is no longer there.

**Comment by DeathCradle** [comment]
I might be missing something here, but I can't seem to see the client sending the favorite flag to the server :c

**Comment by DeathCradle** [comment]
I have confirmed with the tshock crew that favorites are not sent. Unfortunately we cannot support this until the official client sends the data.
