### ISSUE TITLE
Whitelist: Cannot Remove

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#194]
This is the same for both `removeplayer` and `removeip`.
```
8/21/2015 2:04:26 AM Pool> 127.0.0.1:53577 @ 0: ENTER D1G1T4L3CH0
D1G1T4L3CH0 has joined.
8/21/2015 2:04:28 AM Pool> 127.0.0.1:53577: connection closed (Disconnecting).
D1G1T4L3CH0 has left.
whitelist removeplayer D1G1T4L3CH0
8/21/2015 2:04:36 AM Command> Player D1G1T4L3CH0 was removed from the whitelist
8/21/2015 2:04:44 AM Pool> 127.0.0.1:53588 is connecting...
127.0.0.1:53588 is connecting...
8/21/2015 2:04:44 AM Pool> 127.0.0.1:53588 @ 0: ENTER D1G1T4L3CH0
```
Once removing the entry from the file and reloading the whitelist, it does not allow me in.

**Comment by DeathCradle** [comment]
I might have fixed this...Are you able to recheck @D1G1T4L3CH0 ?

**Comment by D1G1T4L3CH0** [comment]
Ok something to note, I'm not certain if this is normal or not. When you connect to the server with whitelist=true, it doesn't know your player's name and in the console log says was botted but no name is there.

**Comment by DeathCradle** [comment]
You are correct about the IP. I need to remove the port and it will work.

**Comment by DeathCradle** [comment]
Hows it now? 10aebc7c843847f4b72d3929041405ecf1fb748d

**Comment by DeathCradle** [comment]
It seems this is fixed. If a time comes when you retest and it doesnt, just reopen this.
