### ISSUE TITLE
Command Request: whoami

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#198]
I think it would be nice to have a /whoami command to know if oyu are authed and as op or not.

**Comment by D1G1T4L3CH0** [comment]
Yay, thanks for this. But as we were chatting about it, here are the notes from that.

it should show auth level, group, and op status

if op status but not actually logged in like with /oplogin if ssc is not used so if the user has op rights but not logged in
maybe something like Operator (not logged in)

an example output might be like: 
`You are [logged in|not logged in] and have auth level of group[ and are an operator].`

**Comment by DeathCradle** [comment]
Alrighty, here's some changes:
![screen shot 2015-09-21 at 6 21 44 pm](https://cloud.githubusercontent.com/assets/776327/9987739/af2b678e-608d-11e5-809c-f8459b88754f.png)
![screen shot 2015-09-21 at 6 21 54 pm](https://cloud.githubusercontent.com/assets/776327/9987738/af2b0a64-608d-11e5-9eb0-e832bab74ce4.png)

**Comment by D1G1T4L3CH0** [comment]
Looks good man. That should be useful from time to time. I'll go ahead and close this one.
