### ISSUE TITLE
Feature Request: Save Interval

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#202]
I think a save interval in the config file would be nice because some people with servers or connections that might go down more often might want to save more often than the default and some who have more reliable servers may want a longer interval.

**Comment by D1G1T4L3CH0** [comment]
Thanks for this. ;)

The only problem I encountered so far is:
save-interval-min=0
means to save as fast as possible :smile:

**Comment by DeathCradle** [comment]
That should be sorted now :)
