### ISSUE TITLE
listgroups Command: Groups Listed Before "Current groups:" String

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#215]
Commit: 9256765f7b6cd55f4fa5634cc80e7613cedeb788

Listing groups with the user command results in the groups to be listed before the "Current groups:" string.

```
user listgroups blah
        Guest
10/1/2015 8:41:41 PM Command> Current groups:
```

**Comment by DeathCradle** [comment]
This should now be fixed in the commit above.
