### ISSUE TITLE
Mysql table creation throwing key too long error

### ISSUE THREAD

**Issue by voh** [DeathCradle/Terraria-s-Dedicated-Server-Mod#224]
Setting the database connection to mysql/mariadb and when creating the tables an error is thrown about the specified key being too long

```
[+] CreateIndex Groups (Name)
!!! Specified key was too long; max key length is 767 bytes
25/05/2016 16:21:01 Run Error> Exception in PreEnable of plugin TDSM Core Module
MySql.Data.MySqlClient.MySqlException: Specified key was too long; max key length is 767 bytes
  at MySql.Data.MySqlClient.MySqlStream.ReadPacket () <0x4104a620 + 0x00193> in <filename unknown>:0
  at MySql.Data.MySqlClient.NativeDriver.GetResult (System.Int32& affectedRow, System.Int64& insertedId) <0x4105ca60 + 0x00037> in <filename unknown>:0
```

The server will continue to start normally but upon world load there will be a null element found error

**Comment by DeathCradle** [comment]
Hi voh

I've made a couple alterations to the migrations, are you able to try again using the latest TDSM.Core.dll?:
https://github.com/DeathCradle/Terraria-s-Dedicated-Server-Mod/raw/master/Binaries/Plugins/TDSM.Core.dll

**Comment by voh** [comment]
After updating TDSM.Core.dll and clearing the DB it does appear it was able to create and populate the tables correctly! Still throws a null element upon loading a world so I guess that is unrelated.

**Comment by DeathCradle** [comment]
I'm glad migrations are working. In regards to the other issue, if possible are you able to screenshot it or copy the error into a new issues please.

**Comment by voh** [comment]
@DeathCradle I don't want to create a whole new issue for what amounts to a minor thing. On the latest update (779c22c) I am getting an error that connector no longer supports versions prior to mysql 5.0, thing is I have MariaDB 10.1, which is most definitely up to date. I don't know if this is just a set-up issue on my end or something else.
