### ISSUE TITLE
Repository info still has a link to defunct tdsm.org

### ISSUE THREAD

**Issue by NightKev** [DeathCradle/Terraria-s-Dedicated-Server-Mod#228]
![outdated website link](https://cloud.githubusercontent.com/assets/849285/16609091/de2a731c-4305-11e6-970a-74a25c27fb14.png)

**Comment by DeathCradle** [comment]
Thanks for letting me know, I've now removed it from that title.
TDSM does not have a website, it was replaced with OTAPI's website.
