### ISSUE TITLE
Sand disappears instead of falling.

### ISSUE THREAD

**Issue by Mctittles** [DeathCradle/Terraria-s-Dedicated-Server-Mod#50]
On build 37 and 39 release when you mine sand from the bottom the entire top layer disappears instead of falling down one block.  

I tried the PreRelease/Debug exe as well and for that sand falls correctly at first but after mining for a bit it starts to disappear again.

I have a guess that sand is treated as a projectile and being limited, but just a guess from a quick skim of the code :)

**Comment by DeathCradle** [comment]
Closed due to the new TDSM.
