### ISSUE TITLE
Players disconnecting when loading tiles (same ip)

### ISSUE THREAD

**Issue by Mctittles** [DeathCradle/Terraria-s-Dedicated-Server-Mod#51]
I'm not sure if having the same ip is the problem but could be relevant.  

When my friends from the same house connect to my server if both of them go in opposite directions and start loading tiles one or both will get a disconnect consistently.  With only one of them on it does not seem to happen.

**Comment by DeathCradle** [comment]
Closed due to the new TDSM.
