### ISSUE TITLE
SPAWNBOSS Command with Wall Of Flesh Outside of Underworld Problems

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#55]
SPAWNBOSS wof If standing on the surface of the world, it spawns the wall of flesh in the sky up high. But only one eye is visible. It does move horizontally across the map as it normally would underground. Maybe it's because it requires a passage like in hell. With a roof. I don't know. But it would seem that there should be a check if there is a character in the correct biome (underworld) and spawn it at that character if so, else, don't spawn it at all because it's messed up if so.

If in underworld, it works fine.

SIde note, if spawned before on the surface, and then spawned in underworld, it has the same problem, except not in the sky, just in some blocks above the player(s). If you go up to his level, it will pull you in and drag you through some blocks until you become stuck inside of them. Restarting the server resolves this.

**Comment by DeathCradle** [comment]
WoF should be spawned in hell/underworld, the new spawnboss command checks for this.
