### ISSUE TITLE
Restrict: Lowercase Passwords

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#58]
Passwords used with capital letters are converted to lowercase. This means the next login, the player will not be able to get in unless they realize this.

For example:
```
/reg TestPassword
PlayerName sent command: /reg testpassword
```

**Comment by DeathCradle** [comment]
This was an issue with how the core dealt with the chat message.
Now fixed in e665a8324988143002c914b7a11dd9fa31e2ef74
