### ISSUE TITLE
Restrict: restrict_users.properties Extra Entry

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#60]
Sometimes it seems there is an extra entry in restrict_users.properties that only has the name without a hash. But below that is the name again, with a hash. The first one is inside < and >.

For example:
```
<playername>=
playername=f5336b91af5c9f489fd55293201729ab2c2d57f10ff529a6f7d4f6d08cecf16f
```

**Comment by DeathCradle** [comment]
With the new data api this will be gone. If the flat file is used, I think it was for compatibility anyway.
