### ISSUE TITLE
Plugin Manager: Plugin Loading Message At Server Start Not Showing Lua Plugins

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#62]
When starting the server, right at the start before it begins loading the world or asking for world selection, it displays something like this:
```
TDSM Rebind API build 1
Loading plugin from RestrictPlugin.dll.
Loading plugin from tdsm.core.dll.
```
However it does not display any Lua plugins. This may be intended though.

**Comment by DeathCradle** [comment]
I simply didn't remember to add the text, it's now in 62444e8565cc256e66452b4e040769763140110d
