### ISSUE TITLE
Dresser:  Disconnect for "Player data sent twice."

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#64]
Using a dresser and confirming your changes results in the following message, and a kick.
` disconnecting for: Player data sent twice.`

Commit: ecd7e2744d3184a3dde8c333f72735cf6bd3215f

**Comment by DeathCradle** [comment]
Alrighty, e594d5e1251fa22d3f05721f83adcb0ccdd29389 should help out.
Let me know how it goes, thanks.

**Comment by D1G1T4L3CH0** [comment]
Confirmed fixed.
