### ISSUE TITLE
Console: Cancelled Explosion

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#68]
The below shows in the console when an explosive is used.
`[TDSM] Cancelled explosive usage of Player: D1G1T4L3CH0`
But it doesn't really cancel the explosion.

**Comment by DeathCradle** [comment]
I've removed explosion and world alterations hooks from the core altogether; as I figure this is mainly a restrict job else it's in the item banning (when implemented again of course).

Commit: 7ffc498f5a279ccc2732be1e8658a2349d79ef80

**Comment by D1G1T4L3CH0** [comment]
Resolved.
