### ISSUE TITLE
Lost Connection / Not enough bandwidth or timed out

### ISSUE THREAD

**Issue by joshhsoj1902** [DeathCradle/Terraria-s-Dedicated-Server-Mod#71]
I am installing TDSM for the first time and it's almost working. I can connect to the server, run around for a little while but after about a minute I am always disconnected with the error "Lost Connection". In the server logs I see the error "02/28/2015 01:57:39 ?> 192.168.0.101:60837 @ 0: disconnecting for: Not enough bandwidth or timed out."

I started looking around the code here, and I found that the error is only written out in Connection.cs when the QueueSize gets to big.

        bool CheckQuota()
        {
            if (QueueSize >= /*Program.properties.SendQueueQuota*/ 1024 * 1024)
            {
                // this is an awful hack but I was in a hurry
                var cc = (ClientConnection)this;
                cc.Kick("Not enough bandwidth or timed out.");
                return false;
            }

            return true;
        }

I don't have an environment that I can use to compile .Net code, so I can't try debugging things. I can see that before the new rebind Program.properties.SendQueueQuota was used. I was hoping to try out an older version of TDSM just to see if it worked but i couldn't find it anywhere...

If there are any other details that you might need from me let me know! (I also would have no issue running an exe with debugging added)

**Comment by DeathCradle** [comment]
Hi there.
I have added the send-queue-quota into the configuration for tweaking. You may find the latest binaries that include this change here: https://github.com/DeathCradle/Terraria-s-Dedicated-Server-Mod/tree/master/Binaries

May I ask what platform you are running TDSM on; and if you are using mono, what version?
This way I can try to replicate as best as possible.

In regards to the old TDSM, I have kept it in the "Retired" directory for occasions such as this. Here's the link to it's binaries: https://github.com/DeathCradle/Terraria-s-Dedicated-Server-Mod/tree/master/Retired/PreRelease
Unfortunately it appears that those are the only binaries since the move and will only support a 1.1.2 client.

**Comment by joshhsoj1902** [comment]
Hi!

No luck so far! With those latest binaries anytime I try to connect I get the message "Only registered users are allowed" Is there a whitelist somewhere I should add myself to? I tried removing the plugin, but then the server wouldn't start.

I haven't tried the older versions yet. I may look into it now.

I am using mono on Debian, and considering Debian's nature it's version of mono may be pretty outdated!

Mono JIT compiler version 2.10.8.1 (Debian 2.10.8.1-8)

After seeing that I decided to try a newer version, so I manually updated to the latest version of mono:

Mono JIT compiler version 3.12.0 (tarball Sat Feb  7 19:12:57 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

But I still got the same "Lost Connection / Not enough bandwidth or timed out" error.

**Comment by D1G1T4L3CH0** [comment]
My mono is 
```
mono --version
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1)
```
 and it works properly. I don't think it's mono anyway.

The only registered users are allowed is a message from the restrict plugin. you could remove the plugin (I think you did?) and the server should have no issues starting. THe file is RestrictPlugin.dll.

You could alternatively use the command `ro -g true` to allow guests.

Also make sure you have ALL of the required files to run the server properly. Get the files located here: https://github.com/DeathCradle/Terraria-s-Dedicated-Server-Mod/tree/master/Binaries You don't really need all of them, take a look at the readme file here: For a list of required files. (I have updated that so it reflects the new files needed)

**Comment by joshhsoj1902** [comment]
Thanks @D1G1T4L3CH0, 

Using the command to allow guests I was able to get in and explore for 5-10 minutes and it never kicked me! 

I just now tried removing the restrict plugin again and the server did start fine! I'm not sure why i had problems with it the first time.

It does indeed look like the newest version works properly! If you guys are satisfied I say we can close off this issue!

**Comment by D1G1T4L3CH0** [comment]
Awesome, so glad you don't continue to have trouble with it. If it happens again, please don't hesitate to make an issue for it.

And thanks for the report, you helped resolve an issue which may have affected others as well. :smile:
