### ISSUE TITLE
Tile memory usage

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#72]
Find a way to get the tile memory usage down.

**Comment by DeathCradle** [comment]
This now needs testing.
As per messages you posted from me on slack, my W10 vm was initially running a large world at 800-900mb, after the new patches in OTA it dropped to about 330mb.
Mono has more overhead, but does gain some, but we need to test the stats on that. 
We also need to review the performance so we can isolate where to speed things up.

TDSM commit: 9df60a583c53899cfe5ef236fdae900e3bdb34f1
OTA commit: ddf97fb5db19ee16cf420b944c90f0d36c1ea52d

**Comment by DeathCradle** [comment]
This is probably it for the time being. There is still a possibility for improvement for memory, as well as optimisations. But in the future when I get time I'll certainly look into it further. If anyone has issues feel free to reopen/create a new one.
