### ISSUE TITLE
Add a web server

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#74]
Add a configurable web server, with management tools.

**Comment by skylord123** [comment]
- Would be great if the webserver had a JSON API for doing various things. 
- Make it so plugins can add their own routes to the webserver for adding API functions as well as adding pages to the web UI.

Mainly I want to make the SQLPlugin deathcradle has been working on have a API function for reloading permissions and groups from the database. I could see this being extremely useful for other things as well.

**Comment by DeathCradle** [comment]
Yeah, that was the intention.

**Comment by DeathCradle** [comment]
This has been implemented, but the API needs building upon in the next few releases.
Anyone, feel free to suggest some API functionality.

**Comment by DeathCradle** [comment]
So this has been in for a while now in the dev changes and this is mainly for the web server, which I believe im happy with. This is now complete. The API spec might have another issue that not bound to a release.
