### ISSUE TITLE
Allow the core to be disabled

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#80]
This is to allow a stock server to be run on linux with no added fu...Please edit this @DeathCradle. I somehow lost the original text at this point. :(

**Comment by DeathCradle** [comment]
This may not be required when terraria is released on Linux/Mac this month.
Happy for a close?

**Comment by D1G1T4L3CH0** [comment]
sure.
