### ISSUE TITLE
Command: SPAWNBOSS - Boss WoF Needs Check

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#90]
Spawning Wall Of Flesh needs a check for if player is <= hell top depth level. If not, the wof is not working correctly and sometimes out of reach.

**Comment by DeathCradle** [comment]
Same as https://github.com/DeathCradle/Terraria-s-Dedicated-Server-Mod/issues/55
