### ISSUE TITLE
Slot Queue Needed

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#93]
We need a better way to make sure we don't send to many npcs or items into the game at a time. The current way is not very good, and I don't think it's accurate either.

For example, spawnnpc 999 "demon eye" just told me the max i could spawn was 4! That's way too low. I'm absolutely certain it can spawn a lot more than that because I have done so before (before that slot check was put in) in the hundreds. Also the spawnnpc command doesn't really spawn all it can, I'm not sure the AvailableSlotItems or NPCItems variables are getting the right numbers.

**Comment by DeathCradle** [comment]
This refers to issue #54, so I'm closing this because the fix will probably make this irrelevant anyway.
