### ISSUE TITLE
Commmand: `time -set` Does Not Update The Client

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#95]
Hen issuing a `time -set` command to set the time to a specific time, it sets the time but does not update the client.

Example: `time dawn`
Result: Time was set to 0 and the client was updated. If the time was night before, the world was dark, but now it is light.

Example: `time -set 0`
Result: Time was set to 0 and the client was not updated. If the time was night before, the world was dark, but the world does not get light.

**Comment by DeathCradle** [comment]
Mind checking out the changes from fea45add6c940034f24f9af78397029821944eb8 onwards?
There is now an additional -day <true|false> flag. (Help text updated in a later commit)

**Comment by DeathCradle** [comment]
*wrong button

**Comment by D1G1T4L3CH0** [comment]
lol. Yeah Ill check it in a few.

**Comment by D1G1T4L3CH0** [comment]
Same issue. Video: https://drive.google.com/file/d/0B-Xui3FKzrq6NFdVVlhzNkt4eXM/view?usp=sharing

**Comment by D1G1T4L3CH0** [comment]
/time set now does update the client, I'll close this. But I think I'll open another one for the new issue we have with it.
