### ISSUE TITLE
help: Too few arguments given.

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#99]
I see there has been work done on implementing help <command>, but now it seems help needs help heh.

When typing the help command without parameters you get:
`help: Too few arguments given.`

Expected result:
A list of commands... or a help command syntax display.

**Comment by DeathCradle** [comment]
Should be fixed in d5de12f89655fd9cb25b84032bed1604f1003bed

**Comment by D1G1T4L3CH0** [comment]
resolved
